# Generated by Django 4.1.3 on 2022-12-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardno', models.IntegerField(auto_created=True)),
                ('content', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('boardfile', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Board',
            },
        ),
    ]
