# Generated by Django 4.1.3 on 2022-12-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_board_id_alter_board_boardno'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
    ]
